import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import CartProduct from '../../components/CartProduct';

const Cart = () => (
    <div>
        <Head>
            <title>Devmite | Your Cart</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* product cart */}
        <div className="container flex flex-col lg:flex-row gap-14">
            <div className="flex flex-col flex-1 gap-3">
                <div className="flex items-center py-4 pl-4 mb-3 border rounded-md pr-9">
                    <input type="checkbox" className="cursor-pointer" />

                    <span className="flex-1 ml-5 font-black tracking-wide text-[8px]">
                        Select All
                    </span>

                    <span className="font-black tracking-wide uppercase cursor-pointer text-[8px] text-[#FF0000]">
                        remove
                    </span>
                </div>

                <CartProduct />
                <CartProduct />
                <CartProduct />
            </div>

            {/* shopping bill */}
            <div className="flex flex-col gap-5 max-h-[247px]">
                <div className="flex flex-col gap-5 px-5 py-4 border rounded-md">
                    <span className="text-xs font-semibold">Shopping Summary</span>

                    <div className="flex items-center justify-between">
                        <span className="font-medium text-[10px]">Total</span>
                        <span className="text-sm font-semibold text-[#493548] dark:text-[#6A8D92]">
                            1,952.66
                        </span>
                    </div>

                    <Link href="/checkout">
                        <button
                            type="button"
                            className="px-20 py-3 font-bold tracking-widest uppercase rounded-md bg-[#493548] text-[10px] text-[#FBFBFB]"
                        >
                            checkout
                        </button>
                    </Link>

                    <span className="self-center font-bold cursor-pointer dark:text-[#6A8D92] text-[#493548] tracking-wide hover:underline text-[9px]">
                        Back to Shopping
                    </span>
                </div>
            </div>
        </div>
    </div>
);

export default Cart;
