import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/router';
import React from 'react';
import { useDispatch } from 'react-redux';
import { addProduct } from '../../../store/cartSlice';

const ProductDetails = () => {
    const dispatch = useDispatch();

    const router = useRouter();
    const { productId } = router.query;

    const product = {
        id: typeof productId === 'string' ? productId : 1,
        name: 'Premium Teeshirt Best High Quality',
        image: 'https://i.pinimg.com/564x/c7/f6/bd/c7f6bdef61e2558147339c0057eee2e8.jpg',
        price: 100,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem magni in laudantium enim sunt deserunt eos hic provident alias veritatis. Quis tempora quia iure quidem! Sit, recusandae quas eius dolores voluptas optio eligendi in facilis deserunt. Earum, consequuntur possimus ad odio officiis, blanditiis consectetur reiciendis incidunt sint magnam eos fugiat!',
    };

    const addToCart = () => {
        dispatch(
            addProduct({
                id: product.id,
                name: product.name,
                image: product.image,
                price: product.price,
            })
        );
    };

    return (
        <div>
            <Head>
                <title>Devmite | Product</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="container">
                {/* navigation */}
                <div className="font-light tracking-wide mb-14 mx-p-w dark:text-[#6A8D92] text-[#493548] text-[10px]">
                    <Link href="/">
                        <span className="cursor-pointer hover:underline">Home</span>
                    </Link>
                    <span className="mx-2">/</span>
                    <Link href="/shop">
                        <span className="cursor-pointer hover:underline">Shop</span>
                    </Link>
                    <span className="mx-2">/</span>
                    <span className="text-xs font-normal">product name</span>
                </div>

                {/* product */}
                <div className="flex flex-col lg:flex-row gap-14">
                    {/* image */}
                    <div className="h-72 w-[400px] flex-shrink-0 relative">
                        <Image src={product.image} layout="fill" objectFit="cover" />
                    </div>

                    {/* details */}
                    <div className="flex flex-col flex-1 gap-3">
                        {/* model */}
                        <span className="text-[#4D4D4D] text-[10px] tracking-wide">
                            {product.id}
                        </span>

                        {/* name */}
                        <span className="text-sm font-bold tracking-wide dark:text-[#6A8D92] text-[#493548]">
                            {product.name}
                        </span>

                        {/* price */}
                        <span className="text-lg font-semibold my-3 uppercase text-[#A1E887]">
                            ${product.price}
                        </span>

                        {/* details */}
                        <span className="text-[11px] tracking-wider">{product.description}</span>

                        {/* add to cart button */}
                        <button
                            type="button"
                            onClick={() => addToCart()}
                            className="flex items-center justify-center w-32 font-bold text-[#FBFBFB] hover:text-[#6A8D92] duration-150 tracking-widest uppercase rounded-md cursor-pointer bg-[#493548] text-[10px] h-9 mt-2"
                        >
                            add to cart
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ProductDetails;
